tl_teleop:
  ros__parameters:
    arm_ip: "192.168.1.13"
    arm_port: "6001"
    arm_port_aux: "7000"
    arm_joints: 7
    pos_scale: 0.5
    pos_deadzone: 0.005
    max_pos_delta_mm: 300.0
    singular_angle: 160.0
    singular_scale: 0.2
    joint_jump_threshold: 30.0
    servo_speed: 25
    publish_rate: 20.0